### ISSUE TITLE
"GET / HTTP/1.1" 404 -

### ISSUE THREAD

**Issue by huxiaoyi520** [ramintoosi/ROSS#10]
python ./ross_backend/app.py
 * Serving Flask app 'app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://10.6.45.126:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 500-095-330
10.6.45.126 - - [11/Mar/2024 05:24:17] "GET / HTTP/1.1" 404 -

Please!  who can help me? thanks very much

**Comment by ramintoosi** [comment]
Check #7 and change ```localhost``` to ```10.6.45.126```.
