### ISSUE TITLE
Startup not working

### ISSUE THREAD

**Issue by jjsakon** [ramintoosi/ROSS#2]
Keep getting this error: <img width="871" alt="image" src="https://user-images.githubusercontent.com/29741844/203211491-5a559b40-4e2e-4a67-a091-11dce00322ae.png">

Same thing happens when I open ross.mlapp and click "Run":
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/29741844/203211614-f4b2de8b-e96f-47c8-957c-85635f9b4764.png">

**Comment by ramintoosi** [comment]
> Keep getting this error: <img alt="image" width="871" src="https://user-images.githubusercontent.com/29741844/203211491-5a559b40-4e2e-4a67-a091-11dce00322ae.png">
> 
> Same thing happens when I open ross.mlapp and click "Run": <img alt="image" width="1142" src="https://user-images.githubusercontent.com/29741844/203211614-f4b2de8b-e96f-47c8-957c-85635f9b4764.png">

Please check if you are using Matlab **2018b or later**. ROSS does not work on Matlab 2018a or earlier.

**Comment by jjsakon** [comment]
It's MatlabR2021b.

**Comment by ramintoosi** [comment]
It seems that Matlab cannot find the functions in the subfolders. We have a piece of code for that in ROSS but something is preventing it from being appropriately implemented. One way to force it is to use addpath function as follows.

`addpath('apps\', 'funcs\', 'configs\')` 
or
`addpath(genpath([ROSS ROOT FOLDER]))`

Please check that and let me know if it works.

**Comment by jjsakon** [comment]
Worked once I went to main folder and added all paths. I think the fact is
downloaded as "ROSS-master" by default instead of "ROSS" made it tricky.
Thanks for the help.

**Comment by ramintoosi** [comment]
Best of luck!
