### ISSUE TITLE
Unknown number of toolboxes necessary

### ISSUE THREAD

**Issue by jjsakon** [ramintoosi/ROSS#3]
ROSS needs a number of toolboxes installed to work. Functions for butter, PCA, sftrans, and many more appear to be necessary. Can a list of the toolboxes required to run ROSS be put on the installation page? It appears at least Signal Processing (for butter) and Statistics and Machine Learning (for PCA). And possibly even FieldTrip?

**Comment by ramintoosi** [comment]
Thanks for the comment. I try to make a list of required toolboxes.

**Comment by jjsakon** [comment]
Hi,
It appears to work well once you install the following:

•statistics and machine learning toolbox

•image processing toolbox

•signal processing toolbox


It might also be important to make sure paths for Fieldtrip aren't loaded,
since some of the functions (e.g. butter.m) share names.


Cheers,

John

**Comment by ramintoosi** [comment]
Thanks!
