### ISSUE TITLE
Adding Dockerfile for Backend

### ISSUE THREAD

**Issue by zhangeLin** [ramintoosi/ROSS#5]
First, I want to express my gratitude for the ROSS software. It helped me in my project, and I truly appreciate your efforts.

I would like to propose an enhancement to the ROSS v2 repository by adding a Dockerfile specifically for the backend part. With the increasing popularity and adoption of containerization technologies, having a Dockerfile can greatly simplify the setup and deployment process for users. It would allow them to quickly spin up the necessary backend environment without having to worry about compatibility issues or complex setup steps.

Given my experience with Docker and the backend requirements of ROSS, I would be more than happy to contribute by providing the Dockerfile. I believe this addition would significantly enhance the usability and accessibility of ROSS for a wider range of users.

**Comment by ramintoosi** [comment]
Thank you for your interest in enhancing the ROSS V2. We are close to releasing the V2-alpha. We would like to encourage you to open a pull request with your changes after the release of V2-alpha. This will allow us to review the Dockerfile and incorporate it into the repository. To streamline the process and ensure that only the Dockerfile is changed, please focus your changes **solely on the Dockerfile**. By keeping the scope of the merge request limited to this specific enhancement, it will be easier for us to review and merge your contribution promptly.  If you have any questions or need assistance during the contribution process, please feel free to ask.
