### ISSUE TITLE
Error: [Errno 98] Address already in use - Issue Report

### ISSUE THREAD

**Issue by brishac** [ramintoosi/ROSS#7]
Hello,

I am currently working with ROSS V2 and encountered an error that I would like to report. Below is the error message I received:

```
* Serving Flask app 'app' (lazy loading)
* Environment: production
WARNING: This is a development server. Do not use it in a production deployment.
Use a production WSGI server instead.
* Debug mode: off
Traceback (most recent call last):
  File "<path_to_file>/app.py", line 106, in <module>
    app.run(host='0.0.0.0', port=5000, debug=False)
  File "<path_to_file>/flask/app.py", line 920, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "<path_to_file>/werkzeug/serving.py", line 1010, in run_simple
    inner()
  File "<path_to_file>/werkzeug/serving.py", line 950, in inner
    srv = make_server(
  File "<path_to_file>/werkzeug/serving.py", line 782, in make_server
    return ThreadedWSGIServer(
  File "<path_to_file>/werkzeug/serving.py", line 688, in __init__
    super().__init__(server_address, handler)  # type: ignore
  File "<path_to_file>/socketserver.py", line 452, in __init__
    self.server_bind()
  File "<path_to_file>/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "<path_to_file>/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

Here are a few details about my environment:

- Operating System: Ubuntu 20.04
- Python Version: 3.10

To provide more context, I received this error while attempting to run the software using the following command:

```bash
python app.py
```

This conflict prevents the software from running.

To help resolve this issue, I would appreciate any guidance or suggestions you can provide. Additionally, if there are any specific steps or configurations I need to follow to avoid this error, please let me know.

**Comment by ramintoosi** [comment]
It appears that the error you're encountering is related to the address being already in use when trying to run ROSS. This typically happens when the port you're trying to use is already being used by another process on your system. To resolve this issue, you can try the following steps:

1. Change the port variable in the last line in ```ross_backend/app.py``` to a number other than 5000, for example, 5001.
2. In the GUI menu, click on ```Options > Server Address```.
3. Modify address (```http://localhost:5000```) according to step 1, for example ```http://localhost:5001```.

**Comment by ramintoosi** [comment]
You can now use ```--port``` to change the server port: 
```
python ./ross_backend/app.py --port 5631 
```
