### ISSUE TITLE
Using issues

### ISSUE THREAD

**Issue by Tevin-yue** [ramintoosi/ROSS#8]
Thank you to the developer, I am quite interested in this project. I encountered some problems during use: 1. When installing, the installation from the yml file seems to always report an error, and finally it can run by installing one by one with pip. Both mac and win systems have been tried, and they cannot be installed normally from yml; 2. An error is always prompted when registering, the local port has been changed, but still cannot register. I hope there can be some detailed explanations for future reference. Thank you.

**Comment by ramintoosi** [comment]
Hi Tevin,
Thanks for your interest. Can you send me the exact error, so I can help you with the software?
Furthermore, the second version is tested on Ubuntu only. If you send your environment yaml file and the OS name you run with, it would be a great help for other users.

**Comment by Tevin-yue** [comment]
Thanks for replying. It raised a connection error and could not establish a new connection. I will change port to try again. The ayttachment is my environment with windows. May it is helpful for others.
[ross_win.zip](https://github.com/ramintoosi/ROSS/files/13541154/ross_win.zip)
